import './globals.css';

import type { Metadata } from 'next';

import { ThemeProvider } from 'internal-ui/theme';

// ----------------------------------------------------------------------

import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <InitColorSchemeScript defaultMode="light" modeStorageKey="theme-mode" />

        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
